data:
  dataset_name: 'stl10'
  data_csv: 'training_data/stl-10/train_labels.json'
  data_dir: 'training_data/stl-10/train_images'
  val_split: 0.2
  num_workers: 4
  img_size: 224

model:
  patch_size: 16
  num_classes: 10 
  in_channels: 3 
  embed_dim: 384
  num_blocks: 3
  num_heads: 6
  mlp_dim: 768
  dropout: 0.25

training:
  random_seed: 42
  batch_size: 112
  num_epochs: 50
  learning_rate: 0.0005
  weight_decay: 0.001
  checkpoint_dir: './checkpoints'